/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCreateEventRouteImport } from './routes/_authenticated/create-event'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as JoinIdRouteImport } from './routes/join.$id'
import { Route as AuthenticatedCheckInIdRouteImport } from './routes/_authenticated/check-in.$id'
import { Route as AuthenticatedDashboardIdRouteImport } from './routes/_authenticated/dashboard.$id'
import { Route as AuthenticatedEditEventIdRouteImport } from './routes/_authenticated/edit-event.$id'
import { Route as AuthenticatedEventIdRouteImport } from './routes/_authenticated/event.$id'
import { Route as AuthenticatedManageEventIdRouteImport } from './routes/_authenticated/manage-event.$id'
import { Route as JoinIdIndexRouteImport } from './routes/join.$id.index'
import { Route as JoinIdRoomIdRouteImport } from './routes/join.$id.$roomId'
import { Route as AuthenticatedDashboardIdMembersRouteImport } from './routes/_authenticated/dashboard_.$id.members'
import { Route as JoinIdConfirmTokenRouteImport } from './routes/join.$id.confirm.$token'
import { Route as AuthenticatedDashboardIdAllowlistTsxRouteImport } from './routes/_authenticated/dashboard_.$id.allowlist.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateEventRoute =
  AuthenticatedCreateEventRouteImport.update({
    id: '/create-event',
    path: '/create-event',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinIdRoute = JoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckInIdRoute = AuthenticatedCheckInIdRouteImport.update({
  id: '/check-in/$id',
  path: '/check-in/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIdRoute =
  AuthenticatedDashboardIdRouteImport.update({
    id: '/dashboard/$id',
    path: '/dashboard/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditEventIdRoute =
  AuthenticatedEditEventIdRouteImport.update({
    id: '/edit-event/$id',
    path: '/edit-event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventIdRoute = AuthenticatedEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageEventIdRoute =
  AuthenticatedManageEventIdRouteImport.update({
    id: '/manage-event/$id',
    path: '/manage-event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinIdIndexRoute = JoinIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinIdRoute,
} as any)
const JoinIdRoomIdRoute = JoinIdRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => JoinIdRoute,
} as any)
const AuthenticatedDashboardIdMembersRoute =
  AuthenticatedDashboardIdMembersRouteImport.update({
    id: '/dashboard_/$id/members',
    path: '/dashboard/$id/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinIdConfirmTokenRoute = JoinIdConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => JoinIdRoute,
} as any)
const AuthenticatedDashboardIdAllowlistTsxRoute =
  AuthenticatedDashboardIdAllowlistTsxRouteImport.update({
    id: '/dashboard_/$id/allowlist/tsx',
    path: '/dashboard/$id/allowlist/tsx',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/create-event': typeof AuthenticatedCreateEventRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/join/$id': typeof JoinIdRouteWithChildren
  '/check-in/$id': typeof AuthenticatedCheckInIdRoute
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/edit-event/$id': typeof AuthenticatedEditEventIdRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/manage-event/$id': typeof AuthenticatedManageEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id/': typeof JoinIdIndexRoute
  '/dashboard/$id/members': typeof AuthenticatedDashboardIdMembersRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
  '/dashboard/$id/allowlist/tsx': typeof AuthenticatedDashboardIdAllowlistTsxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/create-event': typeof AuthenticatedCreateEventRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/check-in/$id': typeof AuthenticatedCheckInIdRoute
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/edit-event/$id': typeof AuthenticatedEditEventIdRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/manage-event/$id': typeof AuthenticatedManageEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id': typeof JoinIdIndexRoute
  '/dashboard/$id/members': typeof AuthenticatedDashboardIdMembersRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
  '/dashboard/$id/allowlist/tsx': typeof AuthenticatedDashboardIdAllowlistTsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/create-event': typeof AuthenticatedCreateEventRoute
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/join/$id': typeof JoinIdRouteWithChildren
  '/_authenticated/check-in/$id': typeof AuthenticatedCheckInIdRoute
  '/_authenticated/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/_authenticated/edit-event/$id': typeof AuthenticatedEditEventIdRoute
  '/_authenticated/event/$id': typeof AuthenticatedEventIdRoute
  '/_authenticated/manage-event/$id': typeof AuthenticatedManageEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id/': typeof JoinIdIndexRoute
  '/_authenticated/dashboard_/$id/members': typeof AuthenticatedDashboardIdMembersRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
  '/_authenticated/dashboard_/$id/allowlist/tsx': typeof AuthenticatedDashboardIdAllowlistTsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/create-event'
    | '/my-events'
    | '/join/$id'
    | '/check-in/$id'
    | '/dashboard/$id'
    | '/edit-event/$id'
    | '/event/$id'
    | '/manage-event/$id'
    | '/join/$id/$roomId'
    | '/join/$id/'
    | '/dashboard/$id/members'
    | '/join/$id/confirm/$token'
    | '/dashboard/$id/allowlist/tsx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/create-event'
    | '/my-events'
    | '/check-in/$id'
    | '/dashboard/$id'
    | '/edit-event/$id'
    | '/event/$id'
    | '/manage-event/$id'
    | '/join/$id/$roomId'
    | '/join/$id'
    | '/dashboard/$id/members'
    | '/join/$id/confirm/$token'
    | '/dashboard/$id/allowlist/tsx'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/create-event'
    | '/_authenticated/my-events'
    | '/join/$id'
    | '/_authenticated/check-in/$id'
    | '/_authenticated/dashboard/$id'
    | '/_authenticated/edit-event/$id'
    | '/_authenticated/event/$id'
    | '/_authenticated/manage-event/$id'
    | '/join/$id/$roomId'
    | '/join/$id/'
    | '/_authenticated/dashboard_/$id/members'
    | '/join/$id/confirm/$token'
    | '/_authenticated/dashboard_/$id/allowlist/tsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  JoinIdRoute: typeof JoinIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-event': {
      id: '/_authenticated/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof AuthenticatedCreateEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$id': {
      id: '/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof JoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/check-in/$id': {
      id: '/_authenticated/check-in/$id'
      path: '/check-in/$id'
      fullPath: '/check-in/$id'
      preLoaderRoute: typeof AuthenticatedCheckInIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$id': {
      id: '/_authenticated/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof AuthenticatedDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-event/$id': {
      id: '/_authenticated/edit-event/$id'
      path: '/edit-event/$id'
      fullPath: '/edit-event/$id'
      preLoaderRoute: typeof AuthenticatedEditEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$id': {
      id: '/_authenticated/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AuthenticatedEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-event/$id': {
      id: '/_authenticated/manage-event/$id'
      path: '/manage-event/$id'
      fullPath: '/manage-event/$id'
      preLoaderRoute: typeof AuthenticatedManageEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$id/': {
      id: '/join/$id/'
      path: '/'
      fullPath: '/join/$id/'
      preLoaderRoute: typeof JoinIdIndexRouteImport
      parentRoute: typeof JoinIdRoute
    }
    '/join/$id/$roomId': {
      id: '/join/$id/$roomId'
      path: '/$roomId'
      fullPath: '/join/$id/$roomId'
      preLoaderRoute: typeof JoinIdRoomIdRouteImport
      parentRoute: typeof JoinIdRoute
    }
    '/_authenticated/dashboard_/$id/members': {
      id: '/_authenticated/dashboard_/$id/members'
      path: '/dashboard/$id/members'
      fullPath: '/dashboard/$id/members'
      preLoaderRoute: typeof AuthenticatedDashboardIdMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$id/confirm/$token': {
      id: '/join/$id/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/join/$id/confirm/$token'
      preLoaderRoute: typeof JoinIdConfirmTokenRouteImport
      parentRoute: typeof JoinIdRoute
    }
    '/_authenticated/dashboard_/$id/allowlist/tsx': {
      id: '/_authenticated/dashboard_/$id/allowlist/tsx'
      path: '/dashboard/$id/allowlist/tsx'
      fullPath: '/dashboard/$id/allowlist/tsx'
      preLoaderRoute: typeof AuthenticatedDashboardIdAllowlistTsxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateEventRoute: typeof AuthenticatedCreateEventRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedCheckInIdRoute: typeof AuthenticatedCheckInIdRoute
  AuthenticatedDashboardIdRoute: typeof AuthenticatedDashboardIdRoute
  AuthenticatedEditEventIdRoute: typeof AuthenticatedEditEventIdRoute
  AuthenticatedEventIdRoute: typeof AuthenticatedEventIdRoute
  AuthenticatedManageEventIdRoute: typeof AuthenticatedManageEventIdRoute
  AuthenticatedDashboardIdMembersRoute: typeof AuthenticatedDashboardIdMembersRoute
  AuthenticatedDashboardIdAllowlistTsxRoute: typeof AuthenticatedDashboardIdAllowlistTsxRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateEventRoute: AuthenticatedCreateEventRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedCheckInIdRoute: AuthenticatedCheckInIdRoute,
  AuthenticatedDashboardIdRoute: AuthenticatedDashboardIdRoute,
  AuthenticatedEditEventIdRoute: AuthenticatedEditEventIdRoute,
  AuthenticatedEventIdRoute: AuthenticatedEventIdRoute,
  AuthenticatedManageEventIdRoute: AuthenticatedManageEventIdRoute,
  AuthenticatedDashboardIdMembersRoute: AuthenticatedDashboardIdMembersRoute,
  AuthenticatedDashboardIdAllowlistTsxRoute:
    AuthenticatedDashboardIdAllowlistTsxRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JoinIdRouteChildren {
  JoinIdRoomIdRoute: typeof JoinIdRoomIdRoute
  JoinIdIndexRoute: typeof JoinIdIndexRoute
  JoinIdConfirmTokenRoute: typeof JoinIdConfirmTokenRoute
}

const JoinIdRouteChildren: JoinIdRouteChildren = {
  JoinIdRoomIdRoute: JoinIdRoomIdRoute,
  JoinIdIndexRoute: JoinIdIndexRoute,
  JoinIdConfirmTokenRoute: JoinIdConfirmTokenRoute,
}

const JoinIdRouteWithChildren =
  JoinIdRoute._addFileChildren(JoinIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  JoinIdRoute: JoinIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
