/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIdRouteImport } from './routes/join.$id'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as AuthenticatedCreateEventRouteImport } from './routes/_authenticated/create-event'
import { Route as JoinIdIndexRouteImport } from './routes/join.$id.index'
import { Route as JoinIdRoomIdRouteImport } from './routes/join.$id.$roomId'
import { Route as AuthenticatedEventIdRouteImport } from './routes/_authenticated/event.$id'
import { Route as AuthenticatedDashboardIdRouteImport } from './routes/_authenticated/dashboard.$id'
import { Route as JoinIdConfirmTokenRouteImport } from './routes/join.$id.confirm.$token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIdRoute = JoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateEventRoute =
  AuthenticatedCreateEventRouteImport.update({
    id: '/create-event',
    path: '/create-event',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinIdIndexRoute = JoinIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinIdRoute,
} as any)
const JoinIdRoomIdRoute = JoinIdRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => JoinIdRoute,
} as any)
const AuthenticatedEventIdRoute = AuthenticatedEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIdRoute =
  AuthenticatedDashboardIdRouteImport.update({
    id: '/dashboard/$id',
    path: '/dashboard/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinIdConfirmTokenRoute = JoinIdConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => JoinIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/create-event': typeof AuthenticatedCreateEventRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/join/$id': typeof JoinIdRouteWithChildren
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id/': typeof JoinIdIndexRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/create-event': typeof AuthenticatedCreateEventRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id': typeof JoinIdIndexRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/create-event': typeof AuthenticatedCreateEventRoute
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/join/$id': typeof JoinIdRouteWithChildren
  '/_authenticated/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/_authenticated/event/$id': typeof AuthenticatedEventIdRoute
  '/join/$id/$roomId': typeof JoinIdRoomIdRoute
  '/join/$id/': typeof JoinIdIndexRoute
  '/join/$id/confirm/$token': typeof JoinIdConfirmTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/create-event'
    | '/my-events'
    | '/join/$id'
    | '/dashboard/$id'
    | '/event/$id'
    | '/join/$id/$roomId'
    | '/join/$id/'
    | '/join/$id/confirm/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/create-event'
    | '/my-events'
    | '/dashboard/$id'
    | '/event/$id'
    | '/join/$id/$roomId'
    | '/join/$id'
    | '/join/$id/confirm/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/create-event'
    | '/_authenticated/my-events'
    | '/join/$id'
    | '/_authenticated/dashboard/$id'
    | '/_authenticated/event/$id'
    | '/join/$id/$roomId'
    | '/join/$id/'
    | '/join/$id/confirm/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  JoinIdRoute: typeof JoinIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$id': {
      id: '/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof JoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-event': {
      id: '/_authenticated/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof AuthenticatedCreateEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$id/': {
      id: '/join/$id/'
      path: '/'
      fullPath: '/join/$id/'
      preLoaderRoute: typeof JoinIdIndexRouteImport
      parentRoute: typeof JoinIdRoute
    }
    '/join/$id/$roomId': {
      id: '/join/$id/$roomId'
      path: '/$roomId'
      fullPath: '/join/$id/$roomId'
      preLoaderRoute: typeof JoinIdRoomIdRouteImport
      parentRoute: typeof JoinIdRoute
    }
    '/_authenticated/event/$id': {
      id: '/_authenticated/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AuthenticatedEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$id': {
      id: '/_authenticated/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof AuthenticatedDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$id/confirm/$token': {
      id: '/join/$id/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/join/$id/confirm/$token'
      preLoaderRoute: typeof JoinIdConfirmTokenRouteImport
      parentRoute: typeof JoinIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateEventRoute: typeof AuthenticatedCreateEventRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedDashboardIdRoute: typeof AuthenticatedDashboardIdRoute
  AuthenticatedEventIdRoute: typeof AuthenticatedEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateEventRoute: AuthenticatedCreateEventRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedDashboardIdRoute: AuthenticatedDashboardIdRoute,
  AuthenticatedEventIdRoute: AuthenticatedEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JoinIdRouteChildren {
  JoinIdRoomIdRoute: typeof JoinIdRoomIdRoute
  JoinIdIndexRoute: typeof JoinIdIndexRoute
  JoinIdConfirmTokenRoute: typeof JoinIdConfirmTokenRoute
}

const JoinIdRouteChildren: JoinIdRouteChildren = {
  JoinIdRoomIdRoute: JoinIdRoomIdRoute,
  JoinIdIndexRoute: JoinIdIndexRoute,
  JoinIdConfirmTokenRoute: JoinIdConfirmTokenRoute,
}

const JoinIdRouteWithChildren =
  JoinIdRoute._addFileChildren(JoinIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  JoinIdRoute: JoinIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
